# Generated by Django 4.0.4 on 2022-05-27 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posttoanotherpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoanotherpost',
            name='post_to_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogpost'),
        ),
    ]
