# Generated by Django 4.0.4 on 2022-05-28 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posttoanotherpost_post_to_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoanotherpost',
            name='post_to_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='blog.blogpost'),
        ),
    ]
