# Generated by Django 4.0.4 on 2022-05-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posttoanotherpost_post_to_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttoanotherpost',
            name='slug',
        ),
    ]
