# Generated by Django 4.0.4 on 2022-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_posttoanotherpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttoanotherpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
